# Database
spring:
  port: 8091
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

# Connection pool properties
connection:
  pool:
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 20
    maxIdleTime: 3000

# Email
mail:
  properties:
    mail:
      smtp:
        auth: false
        starttls:
          enable: true
  host: smtp.gmail.com
  port: 587
  username: yugesh@gmail.com
  password: 1234567890

# Variables
shipping:
  costs: 6.00
